### ISSUE TITLE
Image upload fail with non-existent `uploads_dir` directory

### ISSUE THREAD

**Issue by gruentee** [wkallhof/Hazel#4]
Using the same setup as in [#3](https://github.com/wkallhof/Hazel/issues/3).
Node version:  6.1.0
NPM version:  3.8.6

When an non-existent `uploads_dir` key in `config.json` 

In contrast to the `content_dir` and `data_dir` being created automatically `uploads_dir` is not.
Maybe there should be a consistent default behaviour for all three of them?

Moreover when uploading without a `uploads_dir` the upload progress bar indicates a successful upload, although nothing is actually saved. When hovering over the upload file the pop-over shows "[Object Object]".
That should be changed, too, IMHO.

**Comment by wkallhof** [comment]
@gruentee I just pushed up v1.1.4 which should fix the uploads directory issue. Let me know if you continue to see issues.

**Comment by gruentee** [comment]
I just tested it again (fresh install via npm) and get a slightly different error, screenshot and stack trace attached: 

![screenshot](https://mycloud.biz.tm/owncloud/index.php/s/knG647BCYqKa7uT/download)

```
TypeError: this._uploadImageHandler is not a function
    at StorageProvider.storeFile (/home/connzen/Projekte/node/hazel-test/node_modules/hazel-wiki/app/providers/storageProvider.js:164:21)
    at DocumentController.upload (/home/connzen/Projekte/node/hazel-test/node_modules/hazel-wiki/app/controllers/documentController.js:171:31)
    at Layer.handle [as handle_request] (/home/connzen/Projekte/node/hazel-test/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/connzen/Projekte/node/hazel-test/node_modules/express/lib/router/route.js:131:13)
    at AuthenticationProvider.authenticate (/home/connzen/Projekte/node/hazel-test/node_modules/hazel-wiki/app/providers/authenticationProvider.js:26:20)
    at Layer.handle [as handle_request] (/home/connzen/Projekte/node/hazel-test/node_modules/express/lib/router/layer.js:95:5)
    at next (/home/connzen/Projekte/node/hazel-test/node_modules/express/lib/router/route.js:131:13)
    at Route.dispatch (/home/connzen/Projekte/node/hazel-test/node_modules/express/lib/router/route.js:112:3)
    at Layer.handle [as handle_request] (/home/connzen/Projekte/node/hazel-test/node_modules/express/lib/router/layer.js:95:5)
    at /home/connzen/Projekte/node/hazel-test/node_modules/express/lib/router/index.js:277:22

```

**Comment by wkallhof** [comment]
@gruentee Oops, just pushed up a fix. v1.1.5 should include the fix that properly initializes that variable. Let me know if it continues to cause problems.

**Comment by gruentee** [comment]
Thanks, works now. Maybe it should be mentioned somewhere in the docs (?) that the default behaviour is to create a `uploads` subdirectory under the `hazel` package directory.
